# Generated by Django 6.1.1 on 2026-09-04 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrevistado', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('es_tecnico', models.BooleanField(default=False)),
                ('observaciones_generales', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manejo_datos_personales', models.TextField(help_text='¿Cómo manejan datos sensibles?')),
                ('cumplimiento_nayarit', models.TextField(help_text='Alineación con la Ley de Transparencia de Nayarit')),
                ('reporte_incidentes', models.TextField(help_text='Protocolo actual ante fallas')),
                ('entrevista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.entrevista')),
            ],
        ),
    ]
