# Generated by Django 6.1.1 on 2026-09-04 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrevista',
            name='es_tecnico',
        ),
        migrations.AddField(
            model_name='entrevista',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entrevista',
            name='perfil',
            field=models.CharField(choices=[('ADMIN', 'Personal Administrativo / Ventanilla'), ('TECNICO', 'Infraestructura y Sistemas'), ('TRANSPARENCIA', 'Unidad de Transparencia / Jurídico'), ('FINANZAS', 'Finanzas / Nómina / Tesorería')], default='ADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='cargo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='EvaluacionAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion_accesos', models.TextField(verbose_name='Asignación y uso compartido de credenciales')),
                ('flujo_informacion', models.TextField(verbose_name='Canales de envío de padrones/datos sensibles (WhatsApp, USB, correo)')),
                ('equipos_computo', models.TextField(verbose_name='Uso de equipos institucionales vs. personales (BYOD)')),
                ('respuesta_incidentes', models.TextField(verbose_name='Protocolo ante fallas, bloqueos o sospecha de virus')),
                ('bajas_laborales', models.TextField(verbose_name='Tiempo de revocación de accesos tras renuncia o despido')),
                ('entrevista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eval_administrativa', to='cuestionarios.entrevista')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventario_software', models.TextField(verbose_name='Sistemas principales y aplicaciones legacy sin soporte')),
                ('bases_datos', models.TextField(verbose_name='Motores de base de datos y control de usuarios privilegiados')),
                ('interconexion_apis', models.TextField(verbose_name='Integraciones entre sistemas y exposición de endpoints')),
                ('despliegues_mantenimiento', models.TextField(verbose_name='Procesos de actualización y entornos de prueba')),
                ('monitoreo_logs', models.TextField(verbose_name='Trazabilidad y registro de eventos ante fugas de información')),
                ('estrategia_respaldos', models.TextField(verbose_name='Frecuencia de backups de bases de datos y archivos')),
                ('aislamiento_backups', models.TextField(verbose_name='Resguardo físico/lógico y protección contra ransomware')),
                ('pruebas_recuperacion', models.TextField(verbose_name='Historial y pruebas de restauración ante caídas')),
                ('entrevista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eval_tecnica', to='cuestionarios.entrevista')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionTransparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politica_clasificacion', models.TextField(verbose_name='Políticas alineadas a la Ley de Transparencia de Nayarit')),
                ('versiones_publicas_testado', models.TextField(verbose_name='Procedimiento y herramientas para testar datos (RFC, CURP, firmas)')),
                ('aviso_privacidad', models.TextField(verbose_name='Presencia y difusión de aviso de privacidad integral')),
                ('canales_recepcion_pnt', models.TextField(verbose_name='Manejo y almacenamiento de solicitudes de la PNT en equipos locales')),
                ('archivo_digital_nube', models.TextField(verbose_name='Resguardo de expedientes digitales en nubes (Drive/Dropbox) y cuentas máster')),
                ('entrevista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eval_transparencia', to='cuestionarios.entrevista')),
            ],
        ),
        migrations.DeleteModel(
            name='RespuestaUsuario',
        ),
    ]
