# Generated by Django 6.1.1 on 2026-09-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(choices=[('RED', 'Reestructuración de Red'), ('ACOSO', 'Triage y Acoso Digital'), ('CUMPLIMIENTO', 'Normatividad y Datos'), ('INFRA', 'Infraestructura y Respaldos'), ('OTROS', 'Otros / Juntas')], max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la tarea realizada hoy.')),
                ('horas_invertidas', models.DecimalField(decimal_places=1, default=8.0, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Actividades Diarias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraQuincenal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Primera Quincena Octubre 2026', max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('pagada', models.BooleanField(default=False)),
                ('actividades', models.ManyToManyField(blank=True, to='entregables.actividaddiaria')),
            ],
            options={
                'verbose_name_plural': 'Bitácoras Quincenales',
            },
        ),
        migrations.CreateModel(
            name='ReporteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_reportado', models.CharField(help_text='Ej: Mes 1 - Estabilización y respuesta inmediata', max_length=50)),
                ('que_se_hizo', models.TextField(help_text='Resumen de actividades completadas.')),
                ('que_se_encontro', models.TextField(help_text='Hallazgos relevantes o incidentes.')),
                ('que_sigue', models.TextField(help_text='Próximos pasos para el siguiente mes.')),
                ('bitacoras_relacionadas', models.ManyToManyField(blank=True, to='entregables.bitacoraquincenal')),
            ],
            options={
                'verbose_name_plural': 'Reportes Mensuales',
            },
        ),
    ]
