# Generated by Django 6.1.1 on 2026-09-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Reporte Mensual 1 o Checkpoint Fase 1', max_length=150)),
                ('tipo', models.CharField(choices=[('MENSUAL', 'Reporte Mensual Breve'), ('CHECKPOINT_M4', 'Checkpoint Transición (Mes 4)'), ('TRIMESTRAL', 'Revisión Trimestral (Mes 6, 9, 12)'), ('ANUAL', 'Reporte Ejecutivo Consolidado (Mes 12)')], default='MENSUAL', max_length=20)),
                ('fecha_entrega', models.DateField()),
                ('resumen_ejecutivo', models.TextField(blank=True, verbose_name='Avances / Qué se hizo')),
                ('hallazgos_riesgos', models.TextField(blank=True, verbose_name='Riesgos / Qué se encontró')),
                ('proximos_pasos', models.TextField(blank=True, verbose_name='Ajuste de prioridades / Qué sigue')),
                ('bitacoras_relacionadas', models.ManyToManyField(blank=True, to='entregables.bitacoraquincenal')),
            ],
            options={
                'verbose_name_plural': 'Entregables y Reportes',
                'ordering': ['-fecha_entrega'],
            },
        ),
        migrations.DeleteModel(
            name='ReporteMensual',
        ),
    ]
