# Generated by Django 6.1.1 on 2026-09-04 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('activo_hospedaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.activo')),
            ],
        ),
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_o_usuario', models.CharField(max_length=100)),
                ('nivel_privilegio', models.CharField(max_length=50)),
                ('metodo_autenticacion', models.CharField(max_length=100)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapeo_accesos.sistema')),
            ],
        ),
    ]
